dataset_name: 'guangzhou'
window: 24

adj_threshold: 0.1

detrend: False
scale: True
scaling_axis: 'global'  # ['channels', 'global']
scaled_target: True

epochs: 100
samples_per_epoch: None  # 160 batch of 32
batch_size: 32
aggregate_by: ['mean']
patience: 20

model_name: 'grin'
pred_loss_weight: 0.1

d_hidden: 64
d_emb: 8
d_ff: 64
ff_dropout: 0.0
kernel_size: 2
decoder_order: 1
n_layers: 1
layer_norm: False
merge: 'mlp'
impute_only_holes: True